# 6.pthread_detach 函数  

* 功能：实现线程分离  

* 设置为分离状态的子线程，终止后，会

![image](https://user-images.githubusercontent.com/58176267/173782474-97b088f8-0f8d-45b9-a9ba-8a477e2fd583.png)  


![image](https://user-images.githubusercontent.com/58176267/173782687-02056752-ec66-45a9-8ac4-31f6065dff8f.png)  


## 示例  

* 先创建一个子线程 然后设置该子线程分离   主线程sleep确保子线程函数被执行了  之后主线程使用pthread_join回收子线程  

![image](https://user-images.githubusercontent.com/58176267/173783522-5bf9c6e4-54c4-45c6-9717-2a017f68e99f.png)  
![image](https://user-images.githubusercontent.com/58176267/173783670-87118aac-0fe2-48bf-b70c-479de749087f.png)

* 输出如下  回收子线程时ret返回值是22 不为0意味着回收失败，但是打印错误发现输出了Success  

![image](https://user-images.githubusercontent.com/58176267/173784245-f8206415-7da4-4dde-bc9c-9164d6dcb429.png)  

* 在进程中，很多函数执行成功返回0，失败返回-1或其他，并设置全局变量errno, 然后一直使用上面代码这种方式, 判断不成功就利用perror打印错误信息，perror会在底层访问errno这个全局变量，然后把这个全局变量errno翻译成字符串再拼接上自己传入的字符串，打印在屏幕  
* 但在线程中，使用perror没用了，因为线程的这些函数，成功返回0,失败直接返回的就是错误号errno 
* 比如这里的22实际上就是错误号，因为它并没有去设置全局变量errno，因此使用perror出现了Success  
* 线程代码中如果函数失败，打印22是没意义的，因此可以用 char* strerror(int errnum); 函数(在string.h头文件中)  
* 可利用fprint向标准错误流输出错误信息  

![image](https://user-images.githubusercontent.com/58176267/173786826-d6653a45-7014-4789-97b3-62b841142696.png)  

* 输出如下  
* 使用pthread_join 函数回收时,发现错误信息是 非法参数
* 原因是,子线程设置了分离，主线程sleep了1秒保证了线程会执行完，执行结束后，自己就将残留在PCB中的资源回收了，包括线程ID等，之后再回收，参数tid肯定是非法的  

![image](https://user-images.githubusercontent.com/58176267/173786928-40f8d88f-dd9c-4ecb-9ccb-39162f7d5ca9.png)

